name: Output Issue Event Details
on: 
  issues:
    types: [opened, edited, deleted, labeled, unlabeled, closed, reopened]
  workflow_dispatch: # Add this here

jobs:
  print_event_details:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context for issues event
        run: | 

          echo "Event Name: ${{ github.event_name }}"
          echo "Action: ${{ github.event.action }}"
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue Body: ${{ github.event.issue.body }}"
          echo "Issue URL: ${{ github.event.issue.html_url }}"
          echo "Issue State: ${{ github.event.issue.state }}"
