name: Output Issue Event Details

on:
  issues:
    types: [opened, edited, deleted, labeled, unlabeled, closed, reopened]
jobs:
  print_event_details:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context for issues event
        run: | 

          echo "Event Name: ${{ toJSON(github.event) }}"
          echo "Action: ${{ toJSON(github.event.action) }}"
          echo "Issue Title: ${{ toJSON(github.event.issue.title) }}"
          echo "Issue Body: ${{ toJSON(github.event.issue.body) }}"
          echo "Issue URL: ${{ toJSON(github.event.issue.html_url) }}"
          echo "Issue State: ${{ toJSON(github.event.issue.state) }}"
